coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 15%
        threshold: 2%
        informational: false
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

ignore:
  - "Models/Training/**/*"
  - "NickTests/**/*"
  - "NickIntegrationTests/**/*"
  - "Nick/NickApp.swift"
  - "NickExtension/main.swift"
  - "NickNetFilter/main.swift"
  - "NickHelper/main.swift"
  - "NickUninstaller/NickUninstallerApp.swift"
