// MARK: - Nick
// Copyright © 2026 Ehsan Azish — github.com/EhsanAzish80
// Licensed under AGPL-3.0. See LICENSE for details.

import Foundation

// MARK: - ThreatAlert

/// A correlated, high-confidence threat event produced by `ThreatCorrelator`.
///
/// An alert is synthesised from one or more raw `ThreatSignal` values that
/// collectively satisfy a `CorrelationRule`. The `score` (0–1) reflects the
/// confidence of the rule that fired.
struct ThreatAlert: Identifiable, Sendable, Codable, Equatable {

    /// Stable UUID assigned at creation time.
    let id: UUID

    /// Normalised confidence score in the range [0, 1]. 1.0 = certainty.
    let score: Double

    /// Short human-readable title describing the threat scenario.
    let title: String

    /// Detailed explanation of why this alert was raised.
    let description: String

    /// The most severe signal's severity, promoted where the rule demands it.
    let severity: SignalSeverity

    /// Raw signals that contributed to this alert.
    let contributingSignals: [ThreatSignal]

    /// When the correlation was computed.
    let timestamp: Date

    /// Suggested remediation step for the user.
    let recommendedAction: String

    /// Plain-English explanation generated by `AlertExplainer` (Foundation Models or template).
    /// `nil` until the explanation pipeline has run.
    var explanation: String?

    // MARK: - Init

    init(
        id: UUID = UUID(),
        score: Double,
        title: String,
        description: String,
        severity: SignalSeverity,
        contributingSignals: [ThreatSignal],
        timestamp: Date = Date(),
        recommendedAction: String,
        explanation: String? = nil
    ) {
        self.id = id
        self.score = max(0, min(1, score)) // clamp to [0, 1]
        self.title = title
        self.description = description
        self.severity = severity
        self.contributingSignals = contributingSignals
        self.timestamp = timestamp
        self.recommendedAction = recommendedAction
        self.explanation = explanation
    }

    /// Returns a copy of this alert with a different severity level.
    ///
    /// Used by `ThreatCorrelator` to apply trusted-process severity downgrade
    /// after correlation, without mutating the original value.
    func with(severity: SignalSeverity) -> ThreatAlert {
        ThreatAlert(
            id: self.id,
            score: self.score,
            title: self.title,
            description: self.description,
            severity: severity,
            contributingSignals: self.contributingSignals,
            timestamp: self.timestamp,
            recommendedAction: self.recommendedAction,
            explanation: self.explanation
        )
    }

    /// Stable key that identifies the same logical threat scenario across scan runs.
    ///
    /// Because `id` is a fresh `UUID` on every `correlate()` call, it cannot be
    /// used to recognise a previously-dismissed alert. This key uses the alert title,
    /// severity, and the sorted names of all contributing processes — none of which
    /// change between scans for the same underlying condition.
    var deduplicationKey: String {
        let procNames = contributingSignals
            .compactMap { $0.processInfo?.name }
            .sorted()
            .joined(separator: ",")
        return "\(title)|\(severity.rawValue)|\(procNames)"
    }
}
