// MARK: - Nick
// Copyright © 2026 Ehsan Azish — github.com/EhsanAzish80
// Licensed under AGPL-3.0. See LICENSE for details.

import Foundation

/// Scans `~/Library/Logs` for old system and application log files.
struct LogsRule: ScanRule {
    let category = JunkCategory.logs
    let displayName = "Log Files"

    func scan() async -> [JunkItem] {
        let logDirs: [(URL, String)] = [
            (ScanRuleHelpers.homeURL("Library", "Logs"), "User Logs"),
            (URL(fileURLWithPath: "/Library/Logs"),      "System Logs"),
        ]

        return logDirs.compactMap { (url, label) in
            guard ScanRuleHelpers.exists(url) else { return nil }
            let size = ScanRuleHelpers.size(of: url)
            guard size > 0 else { return nil }
            return JunkItem(url: url, size: size, category: category,
                            riskLevel: .safe, name: label,
                            reason: "Log files generated by macOS and installed applications.")
        }
    }
}
